batch_size: 8
iters: 160000

train_dataset:
  type: Dataset
  dataset_root: chicken_dataset
  train_path: chicken_dataset/train.txt
  num_classes: 3
  transforms:
  - type: ResizeStepScaling
    min_scale_factor: 0.5
    max_scale_factor: 2.0
    scale_step_size: 0.25
  - type: RandomPaddingCrop
    crop_size: [1024, 1024]
  - type: RandomHorizontalFlip
  - type: RandomDistort
    brightness_range: 0.4
    contrast_range: 0.4
    saturation_range: 0.4
  - type: Normalize
  mode: train

val_dataset:
  type: Dataset
  dataset_root: chicken_dataset
  val_path: chicken_dataset/val.txt
  num_classes: 3
  transforms:
  - Resize:
    target_size: [1024, 1024]
  - type: Normalize
  mode: val


optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 4.0e-5


lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.05
  end_lr: 0.0
  power: 0.9

model:
  type: AttentionUNet
  pretrained: Null

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1]
